name: Automerge Dependabot PRs

on:
  pull_request:
    branches:
      - main

jobs:
  merge-me:
    name: Merge me!
    needs:
      - lint
      - docker
      - hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_GITHUB_ACCESS_TOKEN }}
    timeout-minutes: 5
