name: Automerge Dependabot PRs

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Linting

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - # It is often a desired behavior to merge only when a workflow execution
        # succeeds. This can be changed as needed.
        if: ${{ github.event.workflow_run.conclusion == "success" }}
        name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_GITHUB_ACCESS_TOKEN }}
